title: Zhengkai Zhang
email: zzhengkai2017@gmail.com
description: Software engineer working on AI inference and model performance.
url: "https://zhengkaiz.github.io"
baseurl: ""
github_username: ZhengkaiZ
linkedin_username: zhengkaizhang

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
